apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: best-of-backstage-catalog-examples
spec:
  targets:
    - ./components/acr-example.yaml
    - ./components/adr-example.yaml
    - ./components/bookmarks-example.yaml
    - ./components/cicd-statistics-example.yaml
    - ./components/code-climate-example.yaml
    - ./components/code-coverage-example.yaml
    - ./components/entity-feedback-example.yaml
    - ./components/entity-validation-example.yaml
    - ./components/explore-example.yaml
    - ./components/github-actions-example.yaml
    - ./components/jira-example.yaml
    - ./components/kubernetes-example.yaml
    - ./components/nexus-example.yaml
    - ./components/npm-example.yaml
    - ./components/quay-example.yaml
    - ./components/readme-example.yaml
    - ./components/copilot-example.yaml
    - ./components/todo-example.yaml
    - ./template/template.yaml
