apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: code-coverage-example
  annotations:
    backstage.io/code-coverage: enabled
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
