name: Tests

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/tests.yaml
      - backstage/**
      - catalog-examples/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/tests.yaml
      - backstage/**
      - catalog-examples/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [22.x, 24.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}

      - run: yarn install --frozen-lockfile
        working-directory: backstage

      - run: yarn build:all
        working-directory: backstage

      - run: yarn lint:all
        working-directory: backstage

      - run: yarn prettier:check
        working-directory: backstage

      - run: yarn list-deprecations
        working-directory: backstage

      - run: yarn test
        working-directory: backstage

      - run: yarn playwright install chromium
        working-directory: backstage

      - run: yarn test:e2e
        working-directory: backstage

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-node${{ matrix.node_version }}
          path: |
            backstage/e2e-test-report/
            backstage/node_modules/.cache/e2e-test-results/
          retention-days: 3
